[package]
name = "Cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "guessingGame"
path = "src/bin/01GettingStarted&GuessingGame/guessingGame.rs"

[[bin]]
name = "helloWorld"
path = "src/bin/01GettingStarted&GuessingGame/helloWorld.rs"

[[bin]]
name = "higherLowerGuess"
path = "src/bin/01GettingStarted&GuessingGame/higherLowerGuess.rs"

[[bin]]
name = "RandNumber"
path = "src/bin/01GettingStarted&GuessingGame/RandNumber.rs"

[[bin]]
name = "variables_and_mutability"
path = "src/bin/02CommonProgrammingConcepts/variables_and_mutability.rs"

[[bin]]
name = "data_types"
path = "src/bin/02CommonProgrammingConcepts/data_types.rs"

[[bin]]
name = "functions"
path = "src/bin/02CommonProgrammingConcepts/functions.rs"

[[bin]]
name = "control_flow"
path = "src/bin/02CommonProgrammingConcepts/control_flow.rs"

[[bin]]
name = "ownerhip"
path = "src/bin/03UnderstandingOwnership/ownership.rs"

[[bin]]
name = "references_and_borrowing"
path = "src/bin/03UnderstandingOwnership/references_and_borrowing.rs"

[[bin]]
name = "the_slice_type"
path = "src/bin/03UnderstandingOwnership/the_slice_type.rs"

[[bin]]
name = "struct_basics"
path = "src/bin/04structs/struct_basics.rs"

[[bin]]
name = "different_instances"
path = "src/bin/04structs/different_instances.rs"

[[bin]]
name = "rectangle_struct"
path = "src/bin/04structs/rectangle_struct.rs"

[[bin]]
name = "methods"
path = "src/bin/04structs/methods.rs"


[[bin]]
name = "enum_definition"
path = "src/bin/05enums_and_pattern_matching/enum_definition.rs"

[[bin]]
name = "number_analyzer"
path = "src/bin/practice_problems/number_analyzer.rs"

[[bin]]
name = "largest_number"
path = "src/bin/practice_problems/largest_number.rs"

[[bin]]
name = "array_statistics"
path = "src/bin/practice_problems/array_statistics.rs"

[[bin]]
name = "string_inspector"
path = "src/bin/practice_problems/string_inspector.rs"

[[bin]]
name = "modify_through_reference"
path = "src/bin/practice_problems/modify_through_reference.rs"

[[bin]]
name = "ownership_detective"
path = "src/bin/practice_problems/ownership_detective.rs"

[[bin]]
name = "first_word"
path = "src/bin/practice_problems/first_word.rs"


[[bin]]
name = "last_word"
path = "src/bin/practice_problems/last_word.rs"

[[bin]]
name = "structs"
path = "src/bin/practice_problems/structs.rs"

[[bin]]
name = "struct_move_behavior"
path = "src/bin/practice_problems/struct_move_behavior.rs"

[[bin]]
name = "struct_methods"
path = "src/bin/practice_problems/struct_methods.rs"

[[bin]]
name = "enum_traffic_light"
path = "src/bin/practice_problems/enum_traffic_light.rs"

[[bin]]
name = "character_classes"
path = "src/bin/practice_problems/character_classes.rs"