[package]
name = "Cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"

[[bin]]
name = "guessingGame"
path = "src/bin/01GettingStarted&GuessingGame/guessingGame.rs"

[[bin]]
name = "helloWorld"
path = "src/bin/01GettingStarted&GuessingGame/helloWorld.rs"

[[bin]]
name = "higherLowerGuess"
path = "src/bin/01GettingStarted&GuessingGame/higherLowerGuess.rs"

[[bin]]
name = "RandNumber"
path = "src/bin/01GettingStarted&GuessingGame/RandNumber.rs"

[[bin]]
name = "variables_and_mutability"
path = "src/bin/02CommonProgrammingConcepts/variables_and_mutability.rs"

[[bin]]
name = "data_types"
path = "src/bin/02CommonProgrammingConcepts/data_types.rs"

[[bin]]
name = "functions"
path = "src/bin/02CommonProgrammingConcepts/functions.rs"

[[bin]]
name = "control_flow"
path = "src/bin/02CommonProgrammingConcepts/control_flow.rs"

[[bin]]
name = "ownerhip"
path = "src/bin/03UnderstandingOwnership/ownership.rs"

[[bin]]
name = "references_and_borrowing"
path = "src/bin/03UnderstandingOwnership/references_and_borrowing.rs"

[[bin]]
name = "the_slice_type"
path = "src/bin/03UnderstandingOwnership/the_slice_type.rs"

[[bin]]
name = "struct_basics"
path = "src/bin/04structs/struct_basics.rs"

[[bin]]
name = "different_instances"
path = "src/bin/04structs/different_instances.rs"